name: ' Deploy Reference Documentation'

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  pages: write
  id-token: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  DeployALDoc:
    runs-on: [ windows-latest ]
    name: Deploy Reference Documentation
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize the workflow
        id: init
        uses: andersgMSFT/AL-Go-Actions/WorkflowInitialize@PPP
        with:
          shell: powershell
          eventId: "DO0097"
        
      - name: Read settings
        uses: andersgMSFT/AL-Go-Actions/ReadSettings@PPP
        with:
          shell: powershell

      - name: Determine Deployment Environments
        id: DetermineDeploymentEnvironments
        uses: andersgMSFT/AL-Go-Actions/DetermineDeploymentEnvironments@PPP
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          getEnvironments: 'github-pages'
          type: 'Publish'
            
      - name: Setup Pages
        if: steps.DetermineDeploymentEnvironments.outputs.deployALDocArtifact == 1
        uses: actions/configure-pages@v4
        
      - name: Build Reference Documentation
        uses: andersgMSFT/AL-Go-Actions/BuildReferenceDocumentation@PPP
        with:
          shell: powershell
          artifacts: 'latest'
        
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ".aldoc/_site/"
        
      - name: Deploy to GitHub Pages
        if: steps.DetermineDeploymentEnvironments.outputs.deployALDocArtifact == 1
        id: deployment
        uses: actions/deploy-pages@v4
